language: c
compiler:
  - gcc
  - clang
before_script: mkdir build && cd build && cmake ..
script: make && make test
branches:
  only:
    - master
notifications:
  recipients:
    - teh@onetooneandon.to
  email:
    on_success: always
    on_failure: always
